#!/bin/bash

# Load necessary modules
module load FreeBayes
module load bcftools/1.4
module load htslib


# This script takes as input sorted .bam files generated by aligning reads against a
# reference sequence and outputs a consensus .fa sequence using bcftools.

# Loop through barcodes from 01 to 7
for ((i=1; i<=7; i++))
do
    barcode=$(printf "%02d" $i)  # Pad the barcode number with leading zeros if needed
    
	# Variant call to generate VCF from sorted BAM
    freebayes -f data/co1_crab.fasta out/barcode${barcode}/barcode${barcode}.sorted.bam > out/barcode${barcode}/barcode${barcode}.vcf
    
    # Index VCF and gzip for Consensus
    bgzip out/barcode${barcode}/barcode${barcode}.vcf
    tabix out/barcode${barcode}/barcode${barcode}.vcf.gz
    
    # Generate Consensus
	cat data/co1_crab.fasta | bcftools consensus out/barcode${barcode}/barcode${barcode}.vcf.gz > out/barcode${barcode}/barcode${barcode}.consensus.fa

done


